project:
  type: website

website:
  title: "NEXUS: Exposomics in the US"
  google-analytics: "G-L4BSY2WT02"
  favicon: "images/favtightico.jpg"
  site-url: https://www.nexus-exposomics.org
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: news.qmd
        text: News & Views
      - href: contact.qmd
        text: Contact Us
    right: 
      - icon: rss
        href: index.xml

format:
  html:
    theme: cosmo
    mainfont: Helvetica Neue
    css: styles.css
    toc: true
    